HumanCellAtlas/metadata-schema

json_schema/project.json
json_schema/sample.json
json_schema/seq.json

- In project, sample, and seq JSONs combined DDBJ, NCBI, and ENA accession fields for
- runs
- samples
- experiments
- projects
- biosamples
- Fixed minor typos and formatting of the field descriptions
- Fixed formatting for instrument model and platform in seq.json
These changes address issue #48 and comments in v3 metadata feedback doc.

Reorganised INSDC accession fields

---

json_schema/analysis.json
json_schema/assay.json
json_schema/assay_bundle.json
json_schema/cell_suspension.json
json_schema/contact.json
json_schema/death.json
json_schema/donor.json
json_schema/file.json
json_schema/immortalized_cell_line.json
json_schema/organoid.json
json_schema/primary_cell_line.json
json_schema/project.json
json_schema/project_bundle.json
json_schema/protocol.json
json_schema/rna.json
json_schema/sample.json
json_schema/sample_bundle.json
json_schema/seq.json
json_schema/single_cell.json
json_schema/specimen_from_organism.json
json_schema/state_of_specimen.json
json_schema/submission.json

Minor release v4.3.0 include the following changes:
1. Increased max state_of_specimen.ischemic_time and state_of_specimen.postmortem_interval value to 1000000 (#89)
1. Added "10X" and "10x" as options to seq.library_construction, rna.library_construction, and single_cell.cell_handling
1. Updated sample.biosd_sample regex to `^SAM(D|N|E([AG]?))[0-9]+$` (#78)
1. Added "Cambridgeshire" to list of accepted enum values for contact.country_division
1. Updated all URLs to reference 4.3.0
**All changes maintain backwards compatibility.**

V4.3.0 minor release

---

json_schema/assay_bundle.json
json_schema/core.json
json_schema/project_bundle.json
json_schema/sample_bundle.json

- Updated assay_bundle.json and project_bundle.json to be objects instead of arrays
- Added "core" field to assay_bundle.json, project_bundle.json, and sample_bundle.json to inherit type and schema version/URL
- Made core fields required
- Added bundle schemas to list of accepted core types
- Added description to "derived_from" field in sample_bundle.json

Assay/project_bundle.json now objects. Bundle JSONs have core field.

---

json_schema/bundle/biomaterial_bundle.json
json_schema/bundle/ingest.json
json_schema/bundle/process_bundle.json
json_schema/bundle/project_bundle.json
json_schema/bundle/submission.json
schema_test_files/project/test_pass_project_bundle.json
src/json_examples_validate_against_schema.py

General updates to bundle/ingest/submission JSONs:
- Updated bundle descriptions
- Reordered bundle schema attributes to be consistent
- Added "ingest" and "submission" to the enum of `schema_types`
- Added `$schema` to list of required properties where missing
- Added `schema_type` property, `additionalProperties:false`, and `required` where missing
- Changed `$ref` to `id` in `process_bundle.json`
- Removed reference to `core` since we don't use `core.json` anymore
- Updated $refs for subschemas so that they point to the correct subschema
Structural changes specifically to `process_bundle.json`:
- Made the `has_input` property required because we are not allowing submission of a process without supplying which biomaterial/file the process was applied to. Protocols CAN be submitted …

Updated project_bundle schema. Updated automatic test.

---

src/json_to_spreadsheet_template.py

- Including a "purchased_reagents" tab for users to list info about any reagents/kits used in any process. The tab is listed after all process tabs, before the protocol tab. 
- The sequence_file tab was moved to the end.
- Handling of a Process ID header in the purchased_reagents tab for users to link which process used that reagent/kit

Handles a purchased_reagents module.

---

json_schema/core/process/process_core.json
json_schema/type/biomaterial/cell_suspension.json
json_schema/type/biomaterial/organism.json
json_schema/type/process/sequencing/library_preparation_process.json

Minor revisions made based on a global review of all core and type fields in all schemata. Revisions include:
- Changed `name` to `operator_identity` to describe person who did a process. Fixes #123. 
- Changed `sex` to `biological_sex`. Fixes #125.
- Added unit fields for height and weight in `organism.json`. Fixes #126. Fixes #81.
- Changed `total_estimated_cells` from number to integer. Fixes #127.
- Added comment that `library_construction` will become an ontology. Fixes #128. Also referenced in #92.
- Added `medical_history` field to reference module in `organism.json`. Fixes #129.

V5 prototype schema reviews

---

json_schema/module/biomaterial/growth_conditions.json
json_schema/type/biomaterial/cell_line.json
json_schema/type/biomaterial/cell_suspension.json
json_schema/type/biomaterial/organoid.json

This PR is to add a new module - growth_conditions - to the set of biomaterial modules. This module contains fields relating to the growth or maintenance of a biomaterial in culture. This module has been added to the schemas for cell line, organoid, and cell suspension. The changes include:
- Addition of the module - `growth_conditions.json` - to `json_schema/module/biomaterials/`
- Addition of `growth_conditions` field to `cell_line.json`, `cell_suspension.json`, and `organoid.json`
- Removal of `passage_number` field from `cell_line.json` because it is now in the module
- Added missing `user_friendly` attribute to `cell_morphology` field in `organoid.json`

Added a growth_conditions biomaterial module.

---

json_schema/module/biomaterial/preservation_storage.json
json_schema/type/biomaterial/specimen_from_organism.json
schema_test_files/biomaterial/test_fail_biomaterial_bundle.json
schema_test_files/biomaterial/test_pass_biomaterial_bundle.json

This new module contains information that was actually lost from v3, information about how a specimen was preserved and/or stored. Preservation specifically refers to the use of chemicals, cold, or other means to prevent or retard biological or physical deterioration of a biomaterial. Storage specifically refers to how a biomaterial was stored after preservation or before another protocol was used. This module currently is associated with the specimen_from_organism entity, but it is generic enough that we might consider allowing it to be submitted with cell_suspension, cell_line, and organoid. It is probably not relevant for organism.

V5 prototype new preservation/storage module

---

src/json_to_spreadsheet_template.py

Very minor code change in the json schema to template code to fix cross-ref header in dependent tabs (eg biomaterial ID in familial relationship tab etc).

Minor fix to integration of modules as separate tabs

---

json_schema/bundle/process_bundle.json

In copying process_bundle schema from assay bundle schema in v4.6.1, the content of the bundle was pointing to a single process stub schema. In v5, the content block needs to be one of the process type entities.
Changes pass Travis CI tests.
Please delete this branch after merging.

Added oneOf link to process type refs.

---

json_schema/type/biomaterial/organoid.json

I added an example attribute to the organoid_age field in the organoid.json file.

Add example to organoid_age in organoid.json

---

json_schema/bundle/process_bundle.json
schema_test_files/biomaterial/test_fail_biomaterial_bundle.json
schema_test_files/biomaterial/test_pass_biomaterial_bundle.json
schema_test_files/process/test_pass_process_bundle.json
schema_test_files/process/test_pass_sequencing_process.json
src/json_examples_validate_against_schema.py

This PR fixed bundle validation errors. The value for `instrument_manufacturer_model` in the test example process bundle was given as a string, when it actually needs to be an object as this is an ontology field and thus needs to be passed the ontology module.
Also in this PR:
- a single process JSON test example fie (`test_pass_sequencing_process.json`) was added
- a test to validate new process test JSON was added to validation script
- `derived_from` fields in biomaterial bundles were changes to arrays as per the new bundle schema

V5 prototype bundle fixes

---

json_schema/type/process/biomaterial_collection/dissociation_process.json

In v4.6.1, the field was called `cell_handling` in `single_cell.json` and was required. We should maintain this requirement.

Made dissociation_method required to reflect same requirement in v4.

---

json_schema/type/process/sequencing/library_preparation_process.json

The corresponding `molecule` field in v4's `seq.json` schema is required, so the newly named `input_molecule` field should be required, too. It is a necessary field for workflows.

Made input_molecule required as it is in v4.

---

json_schema/type/process/sequencing/library_preparation_process.json
schema_test_files/process/test_pass_process_bundle.json

These fixes should now let Travis CI tests pass. Changes include:
- Updating reference to biological_macromolecule ontology module for `input_molecule` field
- Adding `input_molecule` field to example process bundle

Added new required input_molecule field to test process_bundle.

---

json_schema/type/process/analysis/analysis_process.json

- Removed `analysis_id` as this is now captured in the generic `process_id` field in process_core
- Changed `name` in the definitions to `parameter_name`, `file_name`, and `task_name` to be more specific outside of the context of the definitions (same with `parameter_value` and `file_format`)

Cleaning up v5 analysis.json

---

json_schema/type/biomaterial/specimen_from_organism.json

We need to allow users to declare that their sample represents a certain disease separate from a disease the organism might have that may or may not be related to the disease of the specimen.

Add disease field for specimen. Fixes #11.

---

json_schema/module/biomaterial/death.json
json_schema/type/biomaterial/cell_line.json
json_schema/type/biomaterial/cell_suspension.json
json_schema/type/biomaterial/organism.json
json_schema/type/biomaterial/organoid.json

Removed the extra /<type>/ in `id` URI for biomaterial types.  Also removed `time_of_death` from required list in death.json. It was removed in v4 but crept back in in v5.

V5 prototype remove extra hierarchy from biomaterial types

---

json_schema/type/file/sequence_file.json
json_schema/type/process/sequencing/sequencing_process.json

INSDC run IDs are most associated with individual file(s), so this field makes more sense in the sequencing_file json.

Moved insdc_run to sequence_file.json. Fixes #62.

---

json_schema/bundle/biomaterial.json
json_schema/bundle/file.json
json_schema/bundle/process.json
json_schema/bundle/project.json
json_schema/bundle/protocol.json
schema_test_files/biomaterial/test_fail_biomaterial_bundle.json
schema_test_files/biomaterial/test_pass_biomaterial_bundle.json
schema_test_files/process/test_pass_process_bundle.json
schema_test_files/project/test_pass_project_bundle.json
src/json_examples_validate_against_schema.py

Updates to bundle schemas for v5.0.0 include:
- Changing schema names and title to remove "_bundle" part
- Removing all linking fields (e.g. derived_from)
- Adding a file bundle schema
- Updating example bundle JSON

Malloryfreeberg bundle schema updates

---

json_schema/bundle/biomaterial.json
json_schema/bundle/project.json
json_schema/module/project/publication.json
json_schema/type/biomaterial/cell_line.json
json_schema/type/project/project.json
schema_test_files/biomaterial/test_fail_biomaterial_bundle.json
schema_test_files/biomaterial/test_pass_biomaterial_bundle.json
schema_test_files/project/test_fail_project_0.json
schema_test_files/project/test_pass_project_0.json
schema_test_files/project/test_pass_project_bundle.json

As referenced in Issue #217, `title` should be `publication_title` in the list of required fields in the `publication` module. This change is a patch because it is a bug fix. References to this module in `cell_line.json` and `project.json` were also update to reflect the version change.

Malloryfreeberg bug fix issue217

---

json_schema/type/process/analysis/analysis_process.json

As part of the review of analysis json, we identified that metadata_schema is no longer required as each component schema (eg analysis_file) should be self-describing. metadata_schema was therefore removed.

Analysis json hackathon

---

src/json_to_spreadsheet_template.py

This PR updates the example usages of the json_to_spreadsheet_template.py script located at the bottom of the script. Updates include:
1. Replacing GitHub base URI with schema.humancellatlas.org
1. Adding an additional call to make a spreadsheet with user-friendly headers
1. Adding `--field_names` option to call that generates spreadsheet with JSON fields in header

Updated example commands for running json_to_spreadsheet_template.py.

---

json_schema/module/ontology/biological_macromolecule_ontology.json

Ontologies should be a list, but it was a list inside a single string. 
Detected when programming against the schema 
Fixed the formatting of the allowable ontologies for the biological_macromolecule_ontology.json schema

biological_macromolecule_ontology.json has badly formatted array for ontologies

---

changelog.md
json_schema/bundle/process.json

Release notes
Bug fix to make reference bundle schema reference its own definition with correct version

Patch release to fix incorrect self-reference in process bundle json

---

examples/bundles/v5/Q4DemoSS2PostAnalysis/biomaterial.json
examples/bundles/v5/Q4DemoSS2PostAnalysis/files.json
examples/bundles/v5/Q4DemoSS2PostAnalysis/links.json
examples/bundles/v5/Q4DemoSS2PostAnalysis/process.json
examples/bundles/v5/Q4DemoSS2PostAnalysis/project.json
examples/bundles/v5/Q4DemoSS2PostAnalysis/protocol.json

In order to help green box migrate their subscription queries over to v5 of the metadata (in which they need to query on presence/absence of an analysis process in the bundle), this PR adds a post-analysis bundle example based on the same SS2 example bundle already in the repo. All of the files in this PR are the same as in `examples/bundles/v5/Q4DemoSS2/` except `process.json` also now contains a block of `analysis_process.json` content.

Created a new post-analysis bundle example with v5 metadata.

---

json_schema/module/biomaterial/medical_history.json

**Fixed**
This changes fixes the nutritional_state field in the medical_history module that was missing `"type": "string"` to declare this field as a string. This is a bug fix (i.e. patch change) to the `json_schema/module/biomaterial/medical_history.json` and should increment the patch version by 1.

Added missing type: string to nutritional_state field.

---

src/json_fields_to_csv.py

This PR is for a small python script that extracts all metadata fields in any schema under ./json_schema and puts the property name, user friendly name, description, schema name and whether the property is required or not, into a csv file.
This script is a convenience script for metadata editors. Paths are semi-hardcoded and assume the script is being run from the src directory. Output will be saved to ../docs/jsonBrowser/json_fields.csv. Alternative paths and file names require direct editing of the script as there are no input variables.

Script to extract all json fields into a csv file

---

src/version_update.py

I added the new version update script to the meta-data repo as this is where it will be used
Usage:
Run the python script with the following parameters:
-p ~/path/to/metadata-schema/json_schema
-s module/ontology/species_ontology #path to the entity to update, relative to json_schema
-i patch        #type of update

Version update script

---

changelog.md
json_schema/module/ontology/species_ontology.json
json_schema/versions.json

This change has already been released in master as it was an urgent bug fix but I'm also including it here to avoid future issues when we do the big set of protoco/process changes.
Bug fix to make ontology validation work - root species ontology node changed from "NCBITaxon:131567" to ["OBI:0100026","NCBITaxon:2759"] to reflect usage in HCAO. Patch update to referencing biomaterials and bundles.

Dw species ontology fix

---

changelog.md
json_schema/type/biomaterial/cell_suspension.json
json_schema/versions.json

This PR (Fixes #233) updates the `cell_suspension.json` schema to :
- change `target_cell_type` to `selected_cell_type`
- add missing examples
This is a major change because it changes a field name (essentially removing a field and adding a new field).
Changed the field `target_cell_type` to `selected_cell_type`.

Change target_cell_type to selected_cell_type. Fixes #233.

---

changelog.md
json_schema/type/biomaterial/cell_line.json
json_schema/type/file/reference_file.json
json_schema/type/protocol/analysis/analysis_protocol.json
json_schema/type/protocol/biomaterial_collection/dissociation_protocol.json
json_schema/type/protocol/imaging/imaging_protocol.json

All fields identified in https://docs.google.com/spreadsheets/d/1dQHuiVftSTEqrY85lX1Tr73hDa64do0aBbnhB7_4aJ8/edit#gid=0 as needing to be required were converted to required fields, with the exception of several protocol_type fields, which were recently deprecated in favour of more detailed _method or _approach fields.
This is a major version change as it is not necessarily backwards compatible.
NB: Changelog updated without version numbers. Versions file needs updating.

Made several fields in types required and updated changelog. Fixes #307

---

changelog.md
json_schema/type/biomaterial/donor_organism.json

Fixed typo in `is_living` enum from "unkown" to "unknown"

is_living typo fix in donor_organism schema

---

docs/README.md
docs/committers.md
docs/contributing.md
docs/evolution.md
docs/rationale.md
docs/structure.md

fixes #392
Mulitple *.md files in the markdown have broken links because they are relative to the top of the tree, not the current directory. There are also errors in mailto links. PR coming that shows and corrects this.

Fix broken links in markdown files (issue #392)

---

changelog.md
docs/jsonBrowser/core.md
docs/jsonBrowser/module.md
docs/jsonBrowser/required_fields.md
docs/jsonBrowser/type.md
json_schema/type/protocol/biomaterial_collection/dissociation_protocol.json
json_schema/update_log.csv
json_schema/versions.json

Bug fix: Removed nucleic_acid_source from list of required fields in dissociation_protocol, from which the field was removed (and moved to lib prep schema).
This is a patch update.

Bug fix - Remove nonexistant required field

---

changelog.md
docs/jsonBrowser/core.md
docs/jsonBrowser/module.md
docs/jsonBrowser/required_fields.md
docs/jsonBrowser/type.md
json_schema/module/ontology/organ_ontology.json
json_schema/update_log.csv
json_schema/versions.json

I added embryo and its children as allowed values for organ. The update_log file has  been updated.

Bug fix to organ_ontology by including embryo as allowed value

---

changelog.md
json_schema/update_log.csv
json_schema/versions.json

The original PR made by Zina was prematurely merged (by me). I reversed this (via another PR) and merged back to develop to undo the changes. Despite confirming the differenced between dev and Zina's branch the PR in github was detecting no changes. We were unable to work out why when there clearly were changes. This PR addresses that. Here I took Zina's branch ran the release script properly and now will merge this straight to develop. End result should be the same but the process took 3 PRs rather than one. To remedy this situation Zina has some recommendations to change the instructions a little to make them clearer.

Ran release_prepare.py script. Fixes #596 

---

changelog.md
docs/jsonBrowser/required_fields.md
docs/jsonBrowser/type.md
json_schema/type/file/sequence_file.json
json_schema/update_log.csv
json_schema/versions.json

- add user-friendly name to file_core
- remove "index of the" from lane_index description
- change description of read_index to "The sequencing read this file represents."
- add guidelines to read_index field to indicate that if a sequencing experiment is single-end, enter "read1".
- remove "Can be from the DDBJ, NCBI, or EMBL-EBI. Accession must start with DRR, SRR, or ERR." from description for insdc_run
- add guidelines to insdc_run: "Accession can be from the DDBJ, NCBI, or EMBL-EBI and must start with DRR, SRR, or ERR.".

Sequence file patch updates.

---

src/release_prepare.py

As per recent discussion about the use of change vs changed etc, I've added a warning to the release script if the type isn't part of a defined list. The script will still pass but you should see a warning

Added a printed warning for update types

---

.pullapprove.yml

For `.pullapprove.yaml` file:
- Changed travis check in conditions from `*travis*` to `*[tT]ravis*`
Tested with fnmatch (which is the string comparisor method used in the background) and works for strings `Travis` and `travis`
- Need 1 Reviewers to approve because this is not a schema update
- This PR won't be reviewed

Fix pullapprove config file

---

.pullapprove.yml

Added check_runs.pending check for travis status
This should fix pullapprove failing immediately

Added pending status while travis test is happening

---

.pullapprove.yml
src/schema_linter.py
tests/schema.test.js

When doing a recent PR to schemas we noticed travis tests were failing. I have updated the ontology url as I think that was causing it to fail. I also increased the timeout time as that was causing it to fail too when run locally. Tests now appear to pass locally.
I am not sure if this fix could be incorporated into the other recent PR (#1339) or if it is better to merge this first to enable the the travis tests to succeed for ongoing schema updates.
We are also using this PR to update the pullapprove config so that the correct users are specified for reviews and notifications.
- Need 1 Reviewers to approve because this is not a change to the schemas
- Last Reviewer to review/approve, merge changes by 24 Feb 2021

Fix failing travis tests

---

json_schema/system/file_descriptor.json

Fixes regex issue in https://github.com/HumanCellAtlas/schema-test-data/pull/8/files 
For system/file_descriptor schema:
- changed regex on the DescribedBy field to allow for pointing to staging schemas 
- Need 1 Reviewers to approve because this is a patch update
- Last Reviewer to review/approve, merge changes by 30/04/21

Fixes regex issue in CGMs test data 

---

json_schema/module/protocol/matrix.json

For json_schema/module/protocol/matrix schema:
- L24: Added missing space between `:` and `{`
- L38: Added tabulation to be consistent with the opening of the list
- Added newline at the end of file
- Need 1 Reviewers to approve because this is not any type of semantic update

Linted matrix schema.

---

changelog.md
docs/jsonBrowser/module.md
docs/jsonBrowser/required_fields.md
docs/jsonBrowser/type.md
json_schema/module/process/sequencing/barcode.json
json_schema/type/file/sequence_file.json
json_schema/update_log.csv
json_schema/versions.json

For type/file/sequence_file and module/process/sequencing/barcode:
- Extended read index enum to include read3 and read4
- Extended barcode read enum to include Read 3 and Read 4 
- Need 1 reviewer to approve because this is a patch update
- Last Reviewer to review/approve, merge changes by 25th October

Extended read index enum and barcode read enum. Fixes #1401

---

changelog.md
docs/jsonBrowser/module.md
json_schema/module/ontology/disease_ontology.json
json_schema/update_log.csv
json_schema/versions.json
src/release_prepare.py

Schema update priority ticket with explanation on the change: https://github.com/HumanCellAtlas/metadata-schema/issues/1460
For module/ontology/disease_ontology schema:
- changed restrictions to include `phenotype` branch in the allowed terms.
- This is a minor update
- Last Reviewer to review/approve, merge changes by 27/05/2022

 Expand disease ontology to include phenotype - Fixes #1460 

---

.pullapprove.yml

Linting is now done with GitHub Actions, so the linting status is automatically diplayed when the PR is opened.
This change allows to do both at the same time:
- do the linting
- pullapprove can request reviews on the PR

[HOTFIX] remove linting as failure condition for a PR

---

changelog.md
docs/jsonBrowser/type.md
json_schema/type/protocol/imaging/imaging_preparation_protocol.json
json_schema/update_log.csv
json_schema/versions.json

For `type/protocol/imaging/imaging_preparation_protocol.json` schema:
- Added non-required field `permeabilisation_time`
- Added non-required field `permeabilisation_time_unit`
- Added dependency between permeabilisation_time and permeabilisation_time_unit
- This is a minor update
- Reviews are requested as per usual
Based on the findings by the education team, exposed in the [May 24th demos](https://docs.google.com/presentation/d/10-Ei7SXCqyrLLlWyAGWxS0E02bG6r-sIAumyHBtDoIo/edit#slide=id.g12e39c13645_1_0), we have decided to add the "permeabilisation time" field to the imaging_preparation_protocol to ensure we are capturing the information needed to represent Visium experiments
see #1471

Added permeabilisation time field with time units. Fixes #1471

---

changelog.md
docs/jsonBrowser/core.md
json_schema/core/file/file_core.json
json_schema/update_log.csv
json_schema/versions.json

For `file_core` schema:
- Added value to enum for file source
- This is a minor change to all the schemas it affects (file_core + file type schemas)

Added value 'DCP/2 Ingest' to enum for file source. Fixes #1487.

---

changelog.md
docs/jsonBrowser/core.md
docs/jsonBrowser/type.md
json_schema/core/biomaterial/biomaterial_core.json
json_schema/property_migrations.json
json_schema/type/biomaterial/cell_line.json
json_schema/type/biomaterial/cell_suspension.json
json_schema/type/biomaterial/donor_organism.json
json_schema/update_log.csv
json_schema/versions.json

This is a remake of PR #1513 to clean up the commit tree.
For core/biomaterial/biomaterial_core.json schema:
-Added timecourse module
For type/biomaterial/donor_organism.json schema:
-Removed timecourse module
For type/biomaterial/cell_suspension.json schema:
-Removed timecourse module
For type/biomaterial/cell_line.json schema:
-Removed timecourse module
Reviews requested
-Major change, removing timecourse module from donor_organism, cell_line, and cell_suspension.
-Minor change, adding timecourse module to biomaterial core.

Removed timecourse from types and added to biomaterial core. Fixes #1511

---

changelog.md
docs/jsonBrowser/type.md
json_schema/type/protocol/analysis/analysis_protocol.json
json_schema/update_log.csv
json_schema/versions.json

For `analysis_protocol.json` schema:
- Added `gene_annotation_version` optional field
This field is needed to record the specific Ensembl release version accession number or NCBI RefSeq assembly version.
Is one of the upcoming Tier 1 metadata proposed from HCA Integration Teams & Bionetworks
- Need 5 Reviewers to approve because this is a **minor** update

Added gene_annotation_version field in analysis_protocol.json. Fixes #1543

---

changelog.md
docs/jsonBrowser/type.md
json_schema/type/project/project.json
json_schema/update_log.csv
json_schema/versions.json
src/schema_linter.py

Fixes #1550 
1.  The DUOS id should be required only if the project is managed access (`data_use_restriction = GRU` or `GRU-NCU`)
2. If the project is open access (`data_use_restriction = NRES` ) `DUOS_id` should be forbidden. This way if a project is erroneously marked as open access we can’t export it with a DUOS id.
1. The if block allows to conditionally require a field
2. To make sure that `DUOS_id` is disallowed for open access projects it should be conditionally defined for `data_use_restriction = GRU` or `GRU-NCU`. 
This is not possible because `additionalProperties` is set to false, which means that any property not defined in the main property section will fail validation. Removing `additionalProperties : false` is not an option because then any undeclared property would also be …

adds DUOS id field

---

changelog.md
docs/jsonBrowser/type.md
json_schema/type/protocol/analysis/analysis_protocol.json
json_schema/update_log.csv
json_schema/versions.json

For analysis_protocol.json schema:
- `intron_inclusion`
This field is needed to record whether introns were included in the alignment process during read counting. 
Is one of the upcoming Tier 1 metadata proposed from HCA Integration Teams & Bionetworks
- Need 5 Reviewers to approve because this is a minor update

Added intron_inclusion field in analysis_protocol. Fixes#1554

---

changelog.md
json_schema/system/file_descriptor.json
json_schema/update_log.csv
json_schema/versions.json

Continued from https://github.com/HumanCellAtlas/metadata-schema/pull/1437
The immediate need is for LungMAP but this property could be useful in other contexts as it allows for files to be hosted by DRS implementations other than TDR.
I took Andrew's changes from that old PR, squashed them down into a single commit and removed what I believe to be cruft. The branch is based on staging.

Add `drs_uri` to DCP/2 file descriptor

---

changelog.md

#1597
For [schema_linter.py](https://github.com/HumanCellAtlas/metadata-schema/blob/master/src/schema_linter.py):
- fixed error of array in property type
- added allowed values in `allowed_schema_fields` & "valid JSON types"
- replaced OLS provider url & removed functionality to select OLS environment in script arguments
For [human_readable_json.py](https://github.com/HumanCellAtlas/metadata-schema/blob/master/src/human_readable_json.py):
- fixed bug with numeric enum values
- No reviewers since this is not a schema update

Fixed schema_linter.py and human_readable_json.py script bugs

---

changelog.md
docs/jsonBrowser/type.md
json_schema/type/protocol/biomaterial_collection/dissociation_protocol.json
json_schema/update_log.csv
json_schema/versions.json
src/human_readable_json.py
src/schema_linter.py

#1592 
For `dissociation_protocol.json` schema:
- rename `reagents` friendly name to distinguish with `digestion_solution`
- add `digestion_time`
- add `digestion_time_units`
- add `digestion_temperature`
- add `digestion_solution` 
- Need 5 Reviewers to approve because this is a minor update

Added enzymatic tissue dissociation fields

---

changelog.md
docs/jsonBrowser/module.md
docs/jsonBrowser/required_fields.md
json_schema/module/ontology/medication_ontology.json
json_schema/update_log.csv
json_schema/versions.json

#1604 
For `medication_ontology.json` schema:
- `v2.0.0`: Change the source ontology from [DRON:bfo:0000040](https://www.ebi.ac.uk/ols4/ontologies/dron/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FBFO_0000040?lang=en) to 
* Dietary Supplement - [ncit:C1505](https://www.ebi.ac.uk/ols4/ontologies/ncit/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FNCIT_C1505)
* Bioactive Food Component - [ncit:C54060](https://www.ebi.ac.uk/ols4/ontologies/ncit/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FNCIT_C54060)
* Pharmacologic Substance - [ncit:C1909](https://www.ebi.ac.uk/ols4/ontologies/ncit/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FNCIT_C1909)
* Traditional Chinese Medicine Formulation - …

Updated medication ontology sources

---

changelog.md
docs/jsonBrowser/module.md
docs/jsonBrowser/required_fields.md
docs/jsonBrowser/type.md
json_schema/module/biomaterial/collection_institute.json
json_schema/type/biomaterial/specimen_from_organism.json
json_schema/update_log.csv
json_schema/versions.json

#1606 
For `specimen_from_organism.json` schema:
- Field name: `collection_site`
- Field description: Institute where the biomaterial was collected on.
- Field type: string
- Required: no
- Guidelines: Enter collection site latitude longitude in decimal degrees. If decimal degrees not available use site name or pseudonymized site name.
- Need 4 Reviewers to approve because this is a **major** update

Added collection_institute in specimen_from_organism.Fix#1606
