HumanCellAtlas/metadata-schema

.travis.yml, src/sample_test.py, src/simple_test.py
Adding back test of all schema files for validity as JSON schema.  This may break travis due to problems with analysis.json that we inherited from version_3
=> Adding back simple schema checks

json_schema/common/sample/death.json, json_schema/types/sample/cell_suspension.json, json_schema/types/sample/donor.json, json_schema/types/sample/immortalized_cell_line.json, json_schema/types/sample/organoid.json, json_schema/types/sample/primary_cell_line.json, json_schema/types/sample/sample.json, json_schema/types/sample/specimen_from_organism.json
- Added "id" field to all sample types
- Added "$schema" property to all sample types and populated with regex for json url
- Checked that "sample_core" was in all sample types
- Updated missing descriptions, additionalProperties, title, required for sample types
=> Updated/added id and schema URLs to sample types.

json_schema/core/process/process_core.json, json_schema/core/protocol/protocol_core.json, json_schema/core/sample/sample_core.json, json_schema/types/process/process.json, json_schema/types/protocol/protocol.json, json_schema/types/sample/cell_suspension.json, json_schema/types/sample/sample.json
Updated core JSONs for sample, process, protocol (high-level entities).
=> v5 organisation for sample, process, protocol core.json

README.md
Updated the README specifically for the v5_prototype branch to outline the motivations for what was done.
=> Updated README with v5 description

json_schema/types/sample/organism.json
Updated donor.json, including changing to organism.json
- Renamed "ancestry" field in donor.json #84 
- Renamed "donor" to more generic "organism" #83 
- Moved human-specific and non-human-specific fields up to definitions in organism.json #85
-
=> Updated donor.json to organism.json

json_schema/sample_bundle.json
- removed core from sample_ingest
- added core to sample_bundle
- changed sample_bundle from array type to object type
- added samples field that is an array of samples (pointed to by the key)
=> Updated sample_bundle.json to have core property and array of samples.

json_schema/type/process/sequencing/library_preparation_process.json, src/json_to_spreadsheet.py
Full first pass over the converter plus a typo
=> V5 prototype json to excel

src/json_to_spreadsheet.py, src/json_to_spreadsheet_template.py
=> V5 prototype json excel

contributing.md
Added some instructions for contributing to v5_prototype branch to the contributing.md doc.
=> Updated instructions for contributing changes to v5

src/json_to_spreadsheet_template.py
Fixed dropped ontology modules problem and also added formatting for column width
=> V5 prototype ontology integration in template fix

json_schema/module/ontology/disease_ontology.json, json_schema/module/ontology/mass_unit_ontology.json, json_schema/type/biomaterial/organism.json
Added normal as property option to disease_ontology module, added mass_unit_ontology module and updated height/weight unit in organism to point to relevant ontology modules
=> Ontology module updates

schema_test_files/biomaterial/test_pass_biomaterial_bundle.json, schema_test_files/process/test_pass_process_bundle.json, schema_test_files/project/test_pass_project_bundle.json
All test files fixed and tests now passing. Please merge but don't delete branch so I can use it to close the outstanding PR.
=> V5 prototype schema type updates

json_schema/type/biomaterial/specimen_from_organism.json
Reverted renaming of specimen_from_organism to body_part as this is a major breaking change that will require further discussion and a planned timeline to update dependent testing and software components
=> Fixing of breaking change 

json_schema/core/project/project_core.json, schema_test_files/biomaterial/test_fail_biomaterial_bundle.json, schema_test_files/biomaterial/test_pass_biomaterial_bundle.json, schema_test_files/project/test_fail_project_0.json, schema_test_files/project/test_pass_project_0.json, schema_test_files/project/test_pass_project_bundle.json, src/json_to_spreadsheet_template.py
Script not yet tested as the change isn't in v5_prototype yet.
=> V5 prototype rename project

schema_test_files/project/test_fail_project_0.json, schema_test_files/project/test_pass_project_0.json, schema_test_files/project/test_pass_project_bundle.json, src/json_examples_validate_against_schema.py
Fixed all test files as required
=> Project json examples now fixed and tests passing

json_schema/module/project/contact.json
Moving to format: email for validating email addresses instead of just a pattern.
=> Changed from pattern to format for email field. Fixes #5.

json_schema/type/biomaterial/organism.json
Was fixed in v4.6.1 but this change didn't propagate to v5_prototype.
=> Fixed age, height, and weight to allow ranges.

changelog.md
Created a first changelog doc starting with v3.0 release and current until v4.6.1 release. This doc should be updated after each official release following [Keep a Changelog](http://keepachangelog.com/en/1.0.0/) standards.
=> Created a changelog.md doc.

json_schema/type/biomaterial/organism.json
Added user friendly term to familial_relationship in organism.json.
=> Added user friendly term to familial_relationship in organism.json.

json_schema/type/file/sequence_file.json
Added a `read_length` field to `sequence_file.json`.
=> Added read_length field. Fixes #75.

json_schema/core/biomaterial/biomaterial_core.json, schema_test_files/biomaterial/test_fail_biomaterial_bundle.json, schema_test_files/biomaterial/test_fail_specimen_0.json, schema_test_files/biomaterial/test_pass_biomaterial_bundle.json, schema_test_files/biomaterial/test_pass_specimen_0.json
=> Changed derived_from to has_input_biomaterial in biomaterial_core.json

schema_test_files/process/test_pass_process_bundle.json
Needed to update field names in example process bundle in library_prep_process that were modified.
=> Updated process bundle with modified field names.

json_schema/type/process/sequencing/library_preparation_process.json, schema_test_files/process/test_pass_process_bundle.json
In the required list, updated two field names that were changed. Also changed 5 prime end bias to full length since SmartSeq 2 isn't biased.
=> Updated required field names.

json_schema/type/biomaterial/cell_line.json, json_schema/type/biomaterial/cell_suspension.json, json_schema/type/biomaterial/organism.json, json_schema/type/biomaterial/organoid.json, json_schema/type/biomaterial/specimen_from_organism.json, json_schema/type/process/analysis/analysis_process.json, json_schema/type/process/biomaterial_collection/collection_process.json, json_schema/type/process/biomaterial_collection/enrichment_process.json, json_schema/type/process/imaging/imaging_process.json, json_schema/type/process/sequencing/library_preparation_process.json, json_schema/type/process/sequencing/sequencing_process.json, json_schema/type/project/project.json, json_schema/type/protocol/analysis/analysis_protocol.json, json_schema/type/protocol/biomaterial/biomaterial_collection_protocol.json, json_schema/type/protocol/protocol.json, json_schema/type/protocol/sequencing/sequencing_protocol.json
Also deleted a duplicated description attribute.
=> Fixed annoying indentation inconsistencies.

changelog.md
Added very high level overview of v5 changes to changelog. This should be the final update before v5 release.
=> Final additions to changelog fo v5 release.

issue_template.md, pull_request_template.md
Added a PR template markdown file to top level of the repo. This template will help guide how to form PRs for this repo.
Also made minor edits to the current issues template file.
=> Added a PR template file. Updated issue template file.

docs/jsonBrowser/bundle.md, docs/jsonBrowser/core.md, docs/jsonBrowser/module.md, docs/jsonBrowser/type.md, json_schema/bundle/process.json, json_schema/type/process/process.json, src/human_readable_json.py
Added generic process type to address ingest use case plus associated process bundle update. Also reran human readable json>md script and fixed an incidental bug
Added
type/process/process.json to address an ingest use case whereby each biomaterial has to be linked to a process, so if no process is provided in the metadata, the system can create a generic one
Changed
bundle/process.json - added the new generic process to the list of processes that can be added into the process bundle
=> New generic process type 

changelog.md, json_schema/bundle/reference.json, json_schema/type/file/reference_file.json, schema_test_files/file/test_pass_reference_bundle_0.json
Reference bundle and reference file schemas to v1.0.1 as v1.0.0 was using the wrong version numbers for import references
=> Bug fix for reference bundle and reference file

json_schema/bundle/reference.json, schema_test_files/file/test_pass_reference_bundle_0.json
This PR updates schema refs that pointed to older (1.0.0) schema versions. Also updates the reference bundle example. Examples is valid against its schema.
=> Reference bundle definition now points to newest schema

schema_test_files/process/test_pass_analysis_process.json, src/json_examples_validate_against_schema.py
This PR adds and example analysis_process.json file to the suite of JSON files that run during automatic Travis CI testing. .
=> Added anlaysis_process.json example for testing.

json_schema/type/process/sequencing/library_preparation_process.json
Merging copy of branch into original.
=> Added new amplification fields. Fixes #197.

changelog.md, json_schema/module/biomaterial/growth_conditions.json, json_schema/versions.json
This change is to make the fields mycoplasma_testing_method and mycoplasma_testing_results enums. This is a major change.
=> Added 2 mycoplasma testing fields. Fixes #120

changelog.md, json_schema/type/protocol/analysis/analysis_protocol.json, json_schema/type/protocol/biomaterial_collection/collection_protocol.json, json_schema/type/protocol/biomaterial_collection/dissociation_protocol.json, json_schema/type/protocol/biomaterial_collection/enrichment_protocol.json, json_schema/type/protocol/imaging/imaging_protocol.json, json_schema/type/protocol/protocol.json, json_schema/type/protocol/sequencing/library_preparation_protocol.json, json_schema/type/protocol/sequencing/sequencing_protocol.json
Change log and protocol schemas updated. Versions not updated.
=> Updated all protocol type ontology references to process type

changelog.md, json_schema/module/ontology/enrichment_ontology.json, json_schema/type/protocol/biomaterial_collection/enrichment_protocol.json, json_schema/versions.json
Added enrichment ontology module and updated enrichment_protocol.enrichment_method to use module instead of enum. I added the module to the versions file but didn't update the dependent version numbers, or add version numbers to the change log.
=> Enrichment module

src/version_update.py
=> Bug fix to version number increment

README.md, docs/README.md, docs/images/README.md, docs/jsonBrowser/README.md, examples/README.md, json_schema/README.md, schema_test_files/README.md, src/README.md
This PR includes minor improvements to and additions of README markdown files in various folders.
=> Mf update doc documentation

changelog.md, json_schema/module/ontology/sequencing_ontology.json, json_schema/type/protocol/biomaterial_collection/collection_protocol.json, json_schema/type/protocol/biomaterial_collection/dissociation_protocol.json, json_schema/type/protocol/biomaterial_collection/enrichment_protocol.json, json_schema/type/protocol/sequencing/library_preparation_protocol.json, json_schema/type/protocol/sequencing/sequencing_protocol.json, json_schema/versions.json, schema_test_files/protocol/test_pass_sequencing_protocol.json
Refactored protocol types to remove duplication between *_method and protocol_type, and addition of sequencing_ontology module. Fixes #319
=> Standardize protocol method ontology

changelog.md, json_schema/module/biomaterial/preservation_storage.json, json_schema/versions.json
+### Changed
+Fixed (patch) incorrect user-friendly name.
**NB**: Haven't run version update script. Need to do this once merged into develop. This is a patch update to preservation_storage.json.
=> Mf fix userfriendly issue317

changelog.md, json_schema/type/biomaterial/cell_line.json
Updated the description for the schema.
=> Updated description for cell line. Fixes #314.

changelog.md, json_schema/module/biomaterial/state_of_specimen.json
This is a patch update and should be merged immediately so it can into the release on Monday 11/6/18
=> Updated description of ischemic_time in state_of_specimen. Fixes #334

examples/spreadsheets/current/filled/README.md, examples/spreadsheets/current/template/README.md
This PR adds README markdown files to the repos containing example and template metadata spreadsheets. It fixes #364.
=> Updated readme docs for spreadsheet examples

changelog.md, json_schema/type/biomaterial/cell_line.json, json_schema/versions.json
Patch fix - versions update and changelog already done.
=> Fixed describedBy pattern for cell_line

changelog.md, json_schema/module/ontology/biological_macromolecule_ontology.json, json_schema/module/ontology/cell_cycle_ontology.json, json_schema/module/ontology/cell_type_ontology.json, json_schema/module/ontology/development_stage_ontology.json, json_schema/module/ontology/disease_ontology.json, json_schema/module/ontology/enrichment_ontology.json, json_schema/module/ontology/ethnicity_ontology.json, json_schema/module/ontology/instrument_ontology.json, json_schema/module/ontology/length_unit_ontology.json, json_schema/module/ontology/library_amplification_ontology.json, json_schema/module/ontology/library_construction_ontology.json, json_schema/module/ontology/mass_unit_ontology.json, json_schema/module/ontology/organ_ontology.json, json_schema/module/ontology/organ_part_ontology.json, json_schema/module/ontology/process_type_ontology.json, json_schema/module/ontology/protocol_type_ontology.json, json_schema/module/ontology/sequencing_ontology.json, json_schema/module/ontology/species_ontology.json, json_schema/module/ontology/strain_ontology.json, json_schema/module/ontology/time_unit_ontology.json
Fixes issue #383
This is a minor version increment to all ontology schemas (addition of new optional field).
=> Added optional field ontology_label to all ontology modules

changelog.md, json_schema/module/project/contact.json
Changed descriptions, examples, and user friendly names in the contact module.
=> Updated descriptions and examples in contact module.

changelog.md, json_schema/core/project/project_core.json, json_schema/type/project/project.json
Changed descriptions and examples for fields in the project_core and project_type schemas.
Added some examples to fields in the project_core and project_type schemas.
=> Updated descriptions and examples for project core and type fields

changelog.md, docs/jsonBrowser/bundle.md, docs/jsonBrowser/core.md, docs/jsonBrowser/module.md, docs/jsonBrowser/required_fields.md, docs/jsonBrowser/type.md, json_schema/versions.json
Updated version numbers for latest PR merge.
=> Version error hotfix

examples/bundles/vX/Q4DemoSS2/cell_suspension_0.json, examples/bundles/vX/Q4DemoSS2/dissociation_protocol_0.json, examples/bundles/vX/Q4DemoSS2/donor_organism_0.json, examples/bundles/vX/Q4DemoSS2/enrichment_protocol_0.json, examples/bundles/vX/Q4DemoSS2/library_preparation_protocol_0.json, examples/bundles/vX/Q4DemoSS2/links.json, examples/bundles/vX/Q4DemoSS2/process_0.json, examples/bundles/vX/Q4DemoSS2/process_1.json, examples/bundles/vX/Q4DemoSS2/process_2.json, examples/bundles/vX/Q4DemoSS2/project_0.json, examples/bundles/vX/Q4DemoSS2/sequence_file_0.json, examples/bundles/vX/Q4DemoSS2/sequence_file_1.json, examples/bundles/vX/Q4DemoSS2/sequencing_protocol_0.json, examples/bundles/vX/Q4DemoSS2/specimen_from_organism_0.json
Example bundles with one metadata entry per file
=> one file per entity bundle example

changelog.md, json_schema/module/process/sequencing/10x.json, json_schema/update_log.csv, json_schema/versions.json
=> 10x url fix issue 439

changelog.md, docs/jsonBrowser/module.md, json_schema/update_log.csv, json_schema/versions.json
Now with proper automatic updates using the release_prepare.py script.
=> Ran release_prepare

docs/release_process.md
- Updates to release_process SOP document.
=> Updates to release_process doc

docs/jsonBrowser/core.md, json_schema/core/process/process_core.json, json_schema/update_log.csv
Changed operator_identity and process_location names to operator and location in process core.
=> Process core field changes. Fixes #376 Fixes #377

changelog.md, json_schema/update_log.csv, json_schema/versions.json
=> Ran release prepare script

changelog.md, docs/jsonBrowser/required_fields.md, docs/jsonBrowser/type.md, json_schema/type/biomaterial/donor_organism.json, json_schema/update_log.csv, json_schema/versions.json, schema_test_files/biomaterial/test_pass_donor_organism_0.json
Changed Biological_sex to sex, fixes issue #384.
=> Biological sex shorten.  Fixes #384

changelog.md, docs/jsonBrowser/required_fields.md, docs/jsonBrowser/type.md, json_schema/type/protocol/sequencing/sequencing_protocol.json, json_schema/update_log.csv, json_schema/versions.json
- Changed incorrect "Protocol type" friendly name to "Sequencing approach" for sequencing_approach field.
- Updated update_log.csv
=> Fix friendly name for sequencing approach

changelog.md, docs/jsonBrowser/required_fields.md, docs/jsonBrowser/type.md, json_schema/type/protocol/sequencing/sequencing_protocol.json, json_schema/update_log.csv, json_schema/versions.json, schema_test_files/protocol/test_pass_sequencing_protocol.json
Changed paired_ends to paired_end
=> paired ends to paired end issue #467

docs/jsonBrowser/core.md, docs/jsonBrowser/module.md, docs/jsonBrowser/required_fields.md, docs/jsonBrowser/type.md, docs/metadata_slo.md
In docs folder. Not version changes required, documentation only.
=> New SLO doc

docs/release_process.md
Documentation review: review of the release_process.md 
Addresses Issue#543: Update each document in docs/ folder as per Zina's reviews, which is a part of Epic: Finalize documentation in the metadata-schema repo for phase 1#487
This is documentation change only. No tests needed.
=> Documentation Review: release_process.md Part of #487 and #543

changelog.md, docs/jsonBrowser/core.md, docs/jsonBrowser/module.md, docs/jsonBrowser/required_fields.md, docs/jsonBrowser/type.md, json_schema/module/ontology/organ_ontology.json, json_schema/update_log.csv, json_schema/versions.json
This change is necessary to reduce issues with appropriate term selection.
=> Changed organ_ontology restriction to UBERON:0000465

.github/ISSUE_TEMPLATE/repo_task.md
This PR is to add another issue template for general repo issues that aren't bug reports or schema update requests. Specifically this issue template requests **Acceptance Criteria** to be stated to help with issue prioritization during Sprint Planning.
=> New repo task issue template

docs/committers.md
Fixed example command for pushing changes to new branch.
=> Fixed committers doc. Fixes #578.

json_schema/README.md
- Updated README file for json_schema directory
=> Update schema readme

docs/jsonBrowser/module.md, json_schema/module/protocol/imaging_target.json, json_schema/update_log.csv
The channel field in the Imaging_target module has been made an array. Fixes Issue#596
Run the `src/schemas_are_valid_json.py` and `src/json_examples_validate_against_schema.py` scripts.
Changed update_log.
=> Imaging target channel made an array. Fixes Issue#596

docs/jsonBrowser/module.md, json_schema/module/protocol/imaging_target.json, json_schema/update_log.csv
Reverts HumanCellAtlas/metadata-schema#609
=> Revert "Imaging target channel made an array. Fixes Issue#596"

changelog.md, json_schema/update_log.csv, json_schema/versions.json
Now with release prepare script run...
=> Ran release_prepare.py script.

changelog.md, docs/jsonBrowser/required_fields.md, docs/jsonBrowser/type.md, json_schema/type/biomaterial/cell_suspension.json, json_schema/update_log.csv, json_schema/versions.json
For cell_suspension.json
- add user-friendly name to `biomaterial_core`
- remove example from `selected_cell_type`(example will live in the ontology module)
- remove example from `genus_species` (example will live in the ontology module)
- move "May be 1 for well-based assays." from description to guidelines for `total_estimated_cells` field. Also change to "Enter 1 for well-based assays."
- change "Total estimated cell count" to "Estimated cell count" for `total_estimated_cells` field
=> Cell suspension schema patch updates.

tests/package-lock.json, tests/package.json, tests/schema.test.js
=> sync getFiles()

changelog.md, json_schema/update_log.csv, json_schema/versions.json
Ran release prepare script which was forgotten from PR #667 .
=> Ran release prepare script.

changelog.md, json_schema/update_log.csv, json_schema/versions.json
Project patch updates to adhere to the Style Guide (fixing up PR688 that didn't go through). Fixes#682.
Bug fix.
1 Reviewer
=> ZP Project patch updates. Fixes#682.

tests/package-lock.json, tests/package.json
updated to latest js validator that include fix for https://nodesecurity.io/advisories/737
=> updated validator package to new version that fixes vulnerability

LICENSE
- Add Apache LICENSE file to top level of repo.
=> Add license to repo.

docs/jsonBrowser/core.md, docs/jsonBrowser/module.md, docs/jsonBrowser/required_fields.md, docs/jsonBrowser/type.md, src/human_readable_json.py
There was a bug in the markdown generator script that's now fixed.
=> Fixed the markdown generator script

src/schema_linter.py
No schema changes, just a minor change to the linter script.
=> Fixed issues with linter using import that no longer exists

changelog.md, docs/jsonBrowser/required_fields.md, docs/jsonBrowser/type.md, json_schema/type/file/image_file.json, json_schema/update_log.csv, json_schema/versions.json
Added user-friendly name for file_core in image_file.json. Fixes #798.
- Added user-friendly name for file_core in image_file.json.
- Need 1 Reviewer to approve
- Last to review/approve, merge changes
=> Patch update to image_file.json. Fixes #798.

changelog.md, docs/jsonBrowser/module.md, json_schema/module/ontology/ethnicity_ontology.json, json_schema/update_log.csv, json_schema/versions.json
- Hancestro example changed to colon so automatically generated sheets validate.
- Need 1 Reviewer to approve
- Merge by Friday 15th.
- Last to review/approve, merge changes
=> Hancestro update example to include colon Fixes #818

docs/jsonBrowser/module.md, docs/jsonBrowser/required_fields.md, docs/jsonBrowser/type.md, src/schema_linter.py
For schema_linter.py
-  Added condition that excludes top-level JSON files from being tested by linter.
- Need 1 Reviewers to approve because this is a code update
- Last to review/approve, merge changes
=> Updated linter to exclude top-level JSON files.

security.txt
No schema changes.
Added security.txt file to repo. 
None requested.
=> Added security text. Fixes #867.

json_schema/property_migrations.json
No schema changes.
Updated property_migrations.json to include 3 more major schema updates. 
- Need @daniwelter to approve because the migration file was manually updated
- Last to review/approve, merge changes
- PR should be merged prior to dev -> int release
=> Update migration JSON with dev -> int release major updates

docs/test_plan.md
Initial proposal for metadata schema test plan, for review only, please do not merge.
=> first pass at a test plan for the metadata schema

changelog.md, json_schema/update_log.csv, json_schema/versions.json
This is a fix for incorrect PR. 
No reviewers necessary, I will merge myself.
=> Fix incorrect PR for Issue893

changelog.md, json_schema/update_log.csv, json_schema/versions.json
This is a fix for the previous PR.
No reviewers needed.
=> Ran release_prepare.py

docs/release_process.md
No schemas changed.
Added instructions for triggering integration test. 
Removed out-of-date instructions for checking caching of schema changes (caching doesn't happen anymore).
No reviewers needed.
=> Added how to launch integration test. Fixes #902.

docs/jsonBrowser/core.md, docs/jsonBrowser/module.md, docs/jsonBrowser/required_fields.md, docs/jsonBrowser/type.md, json_schema/property_migrations.json
This migration was for a patch release and therefore should not have been included
This PR does not require any reviews as it is a bug fix to non-schema file.
=> Deleted the imaging_protocol migration in property_migrations.json

changelog.md, docs/jsonBrowser/core.md, docs/jsonBrowser/module.md, docs/jsonBrowser/required_fields.md, docs/jsonBrowser/type.md, json_schema/property_migrations.json
A single non-schema hotfix to the property_migrations.json file needs to be pushed to integration before the next round of staging and production releases can go ahead.
=> Hotfix from develop to integration

src/schema_linter.py
For `src/schema_linter.py`:
- Changed line 77 from `if properties['describedBy']['pattern'].split("/")[-1] != schema_filename:` to `if "describedBy" in schema and properties['describedBy']['pattern'].split("/")[-1] != schema_filename:`
- Need 1 Reviewers to approve because this is a script update
- Last Reviewer to review/approve, merge changes by 18/06/2019 (Can merge myself since it's a really little update)
=> Fixed small bug with schema linter. Fixes #1024

src/schema_linter.py
For `src/schema_linter.py` script:
- added block of code on line 77:
```
if 'description' in schema and not re.match('^[A-Z][^?!]*[.]$',schema['description']):
warnings.append(schema_filename + ".json: The `description` of the schema is not a sentence (" +
schema['description'] + ").")
```
- Need 1 Reviewers to approve because this is a minor script addition.
- Last Reviewer to review/approve, merge changes by 19/06/2019
=> Added code to check for schema description on line 77. Fixes #1031

docs/release_process.md
- No schema updates. 
- Updated text in release_process.md document describing when to do primary release (dev -> integration). Fixes #1057 
- Need 1 Reviewers to approve because this is a documentation change
- Last Reviewer to review/approve, merge changes by **Friday 5 July**
=> Added when primary release should happen. Fixes #1057.

src/README.md, src/human_readable_json.py, src/release_prepare.py, src/version_update.py
Documentation updates as part of my handover work. No schema changes so can be merged in any time.
1 reviewer required, last reviewer to merge changes.
=> Updated src/ readme and commented some of the metadata scripts

changelog.md, json_schema/core/biomaterial/biomaterial_core.json, json_schema/update_log.csv, json_schema/versions.json
For `biomaterial_core` schema:
- Changed pattern matching of property `schema_version` to properly detect version numbers.
- Changed pattern matching of property `insdc_sample_accession` to avoid detecting `|` as valid.
- Need 2 Reviewers to approve because this is a minor update
- Last Reviewer to review/approve, merge changes by 02/09/2019
=> Fixed regex pattern matchings in Biomaterial_core. Fixes #1090

.pullapprove.yml
This is a code enhancement to the config file.
Fixed old unexpected bejaviour(s):
- Now it won't fail automatically if trying to merge a release, security update or hotfix to a branch other than develop (It will still fail if trying to merge from a branch to any environment other than develop).
Added new functionalities:
- Notification of major schema updates to @maniarathi @aaclan-ebi @MDunitz @NoopDog @brianraymor @jahilton @jychien @jlzamanian @samanehsan @hannes-ucsc @kislyuk
- Added code review group
- Added security updates review group and automatic notification to @ESapenaVentura  when Snyk opens a PR.
- Need 1 Reviewers to approve because this is a code update
- Last Reviewer to review/approve, merge by 06/09/2019
=> Updated pullapprove config file. Fixes #1109.

.pullapprove.yml, tests/.snyk, tests/package.json
Snyk and pullapprove security updates. No version or functionality changes.
=> Release from integration to staging - 2019-10-02

.github/ISSUE_TEMPLATE/schema_update.md
No schema changes.
For `.github/ISSUE_TEMPLATE/schema_update.md`:
- Added line in template example to account for the type of change that the update wants to introduce.
- Need 1 Reviewers to approve.
- Last Reviewer to review/approve, merge changes by 13/11/2015
=> Updated schema_update.md template to indicate type of update.Fixes #1160

.github/ISSUE_TEMPLATE/schema_update.md, .travis.yml, src/schema_linter.py
No schema changes. Minor changes to issue template.
Functionality changes:
Updated schema linter to indicate environment for the OLS API URL
Updated travis config to use the environment proper environment when executing the schema linter.
=> Release from integration to staging 2019-11-27

docs/schema_style_guide.md, json_schema/README.md, src/README.md
No Schema changes. 
Documentation changes:
- Added section to the `schema_style_guide.md` document for the schema linter. This section includes a markdown table that shows all the checks the schema linter checks against.
- Added line at the `Readme.md` document inside the `json_schema/` folder to indicate that rules are tested automatically on every push to github.
- Added a couple of lines to the `Readme.md` document inside the `src/` folder to show how to use locally if needed.  Human friendly check-list is also pointed out.
- Need 1 or 2 Reviewers to approve because this is a documentation update
- Last Reviewer to review/approve, merge changes by 16/12/2019
=> Schema linter documentation update - Fixes #1170

changelog.md, json_schema/system/links.json, json_schema/update_log.csv, json_schema/versions.json, tests/schema.test.js, tests/schema_test_files/system/test_pass_links.json
For links.json schema:
- Each link entry now entirely captures a Process, as well as its inputs, outputs, and protocols
This is a hotfix for `links.json` schema update.
=> [HOTFIX - Integration] Updated links.json for the DCP2 MVP.  Fixes #1278

changelog.md, json_schema/system/links.json, json_schema/update_log.csv, json_schema/versions.json, tests/schema.test.js, tests/schema_test_files/system/test_pass_links.json
For links.json schema:
- Each link entry now entirely captures a Process, as well as its inputs, outputs, and protocols
This is a hotfix for `links.json` schema update.
=> [HOTFIX - Staging] Updated links.json for the DCP2 MVP.  Fixes #1278

changelog.md, json_schema/system/links.json, json_schema/update_log.csv, json_schema/versions.json, tests/schema.test.js, tests/schema_test_files/system/test_pass_links.json
For links.json schema:
- Each link entry now entirely captures a Process, as well as its inputs, outputs, and protocols
This is a hotfix for `links.json` schema update.
=> [HOTFIX - Prod] Updated links.json for the DCP2 MVP.  Fixes #1278

changelog.md, docs/jsonBrowser/required_fields.md, docs/jsonBrowser/type.md, json_schema/property_migrations.json, json_schema/type/process/analysis/analysis_process.json, json_schema/update_log.csv, json_schema/versions.json, tests/schema_test_files/process/test_pass_analysis_process.json, tests/schema_test_files/process/test_pass_new_analysis_process.json
For `type/process/analysis/analysis_process.json` schema:
- Removed `input_bundles`
- Changed `reference_bundle` to `reference_files` and updated the field's properties.
- Changed required fields to reflect the new property name and removal of input_bundles.
- Need 2 Reviewers to approve because this is a major update
- This update will be applied to all environments once it's approved.
=> Changed reference_bundle to files and removed input_bundles. Fixes #1275 and #1290

changelog.md, docs/jsonBrowser/required_fields.md, docs/jsonBrowser/type.md, json_schema/property_migrations.json, json_schema/type/process/analysis/analysis_process.json, json_schema/update_log.csv, json_schema/versions.json, tests/schema_test_files/process/test_pass_analysis_process.json, tests/schema_test_files/process/test_pass_new_analysis_process.json
For `type/process/analysis/analysis_process.json` schema:
- Removed `input_bundles`
- Changed `reference_bundle` to `reference_files` and updated the field's properties.
- Changed required fields to reflect the new property name and removal of input_bundles.
- This update will be applied to all environments once it's approved.
=> [STAGING] Changed reference_bundle to files and removed input_bundles. Fixes #1275 and #1290

changelog.md, docs/jsonBrowser/required_fields.md, docs/jsonBrowser/type.md, json_schema/property_migrations.json, json_schema/type/process/analysis/analysis_process.json, json_schema/update_log.csv, json_schema/versions.json, tests/schema_test_files/process/test_pass_analysis_process.json, tests/schema_test_files/process/test_pass_new_analysis_process.json
For `type/process/analysis/analysis_process.json` schema:
- Removed `input_bundles`
- Changed `reference_bundle` to `reference_files` and updated the field's properties.
- Changed required fields to reflect the new property name and removal of input_bundles.
- This update will be applied to all environments once it's approved.
=> [INTEGRATION] - Changed reference_bundle to files and removed input_bundles. Fixes #1275 and #1290

docs/release_process.md
For `docs/release_process.md` document:
- Added `how-to` section for hotfixes
- Need as many reviewers as possible to approve because this is process documentation update.
=> Added hotfix section. Fixes #1298.

changelog.md, json_schema/system/links.json, json_schema/update_log.csv, json_schema/versions.json
For system/links schema:
- Added full link to refs so that urls resolve properly
- Need 1 Reviewer to approve because this is a patch update
- Last Reviewer to review/approve, merge changes by 25/06/2020
=> Hotfix: Fix refs links in links.json Fixes #1303

changelog.md, json_schema/system/links.json, json_schema/update_log.csv, json_schema/versions.json
For links.json schema:
- fixed ref links
=> Hotfix: fix links in links.json fixes #1303

changelog.md
Because I have now released the links.json change on master I need to manually update the changelog to reflect this.
=> manually updated changelog for links hotfix

changelog.md, json_schema/system/file_descriptor.json, json_schema/update_log.csv, json_schema/versions.json
Added a new 'file_descriptor.json' schema under system for storing file information such as checksums, size, version etc.
- This PR was already reviewed in issue #1302 but because develop was used as the base branch I have moved all changes to a fresh branch for merging into master
=> Hotfix: Add file descriptor schema. Fixes #1289

changelog.md, json_schema/system/file_descriptor.json, json_schema/update_log.csv, json_schema/versions.json
Added new system/file_descriptor.json schema
- This has been reviewed in a previous PR #1302
=> Hotfix: add file_descriptor.json

changelog.md, json_schema/property_migrations.json, json_schema/system/file_descriptor.json, json_schema/versions.json
Reverts HumanCellAtlas/metadata-schema#1323 because I overwrote other changes
=> Revert "Remove major/minor version fields from file_descriptor Fixes #1317"

.pullapprove.yml, docs/jsonBrowser/type.md
No changes made to schemas.
For `.pullapprove.yml`:
- Made changes as requested in ticket #1287
=> Changed pullapprove lists acording to ticket. Fixes #1287

.pullapprove.yml
Changed pullapprove travis check from statuses to check_runs
=> [HOTFIX] Changed travis check from statuses to check_runs

.pullapprove.yml
Fixed pullapprove config file, pending does not exist in CheckRuns object
=> fixed check_runs object in conditions

.pullapprove.yml
Testing success endpoint for pullapprove checks
=> Tried with success endpoint instead of successful

.pullapprove.yml, changelog.md, json_schema/system/links.json, json_schema/update_log.csv, json_schema/versions.json, src/schema_linter.py, tests/package-lock.json, tests/schema.test.js, tests/schema_test_files/system/test_fail_links.json
For `system/links.json` schema:
- `protocol_type`: Changed from free string to enum of values 
Also not related to the schema update but I issued a quick hotfix for the schema linter (Addressed in issue #1294 )
- Need 2 Reviewers to approve because this is a major update 
- Last Reviewer to review/approve, merge changes by 29/02/2021
=> Changed protocol type in links schema to enum. Fixes #1333

docs/jsonBrowser/type.md, json_schema/type/project/project.json, json_schema/update_log.csv
For type/project schema:
- added ega_accessions field to capture EGA Study and Dataset accessions
- added dbgap_accessions field to capture dbgap study accessions
- Need 2 Reviewers to approve because this is a minor update
- Last Reviewer to review/approve, merge changes by Tuesday 23rd of March
=> added ega, dbgap accessions. Fixes #1336

docs/jsonBrowser/type.md, json_schema/type/project/project.json, json_schema/update_log.csv
Reverts HumanCellAtlas/metadata-schema#1366 
Didn't run release_prepare.py
=> Revert "added ega, dbgap accessions. Fixes #1336"

changelog.md, json_schema/update_log.csv, json_schema/versions.json
=> [Hotfix] Ran release_prepare.py script for ega/dbgap PR

changelog.md, docs/jsonBrowser/type.md, json_schema/property_migrations.json, json_schema/type/project/project.json, json_schema/update_log.csv, json_schema/versions.json, tests/schema_test_files/project/test_pass_project_0.json
For `project.json` schema:
- remove `data_use_restrictions` field
- Need 1 Reviewers to approve because this is a major update but it's a rollback
- Last Reviewer to review/approve, merge changes by 25/03/2021
=> Roll back data_use_restrictions field in project schema

json_schema/module/protocol/matrix.json
For json_schema/module/protocol/matrix schema:
- L27-37: Fixed tabulation
- Need 1 Reviewers to approve because this is not any type of semantic update
=> Fixed tabulation issue

docs/committers.md, docs/release_process.md
For `docs/commiters.md`:
- Added pre-requisites
- Updated obsolete information about commiting process
For `docs/release_process.md`:
- Updated environments
- Updated outdated documentation
- Need wranglers to review as this is an SOP change
=> Reviewed with new guidelines for commiting changes.

docs/committers.md, docs/release_process.md
For `docs/commiters.md`:
- Added pre-requisites
- Updated obsolete information about commiting process
For `docs/release_process.md`:
- Updated environments
- Updated outdated documentation
- This has already been reviewed in the prod environment
=> Reviewed with new guidelines

changelog.md, json_schema/module/ontology/file_content_ontology.json, json_schema/update_log.csv, json_schema/versions.json
Schema update priority ticket with explanation on the change: https://app.zenhub.com/workspaces/operations-5fa2d8f2df78bb000f7fb2b5/issues/ebi-ait/hca-ebi-wrangler-central/695
For module/ontology/file_content_ontology schema:
- Changed restrictions to allow `Information` branch to the allowed terms.
=> Added information branch to graphRestrictions. Fixes #1450

changelog.md, docs/jsonBrowser/module.md, json_schema/module/ontology/disease_ontology.json, json_schema/module/ontology/file_content_ontology.json, json_schema/versions.json, src/release_prepare.py
**Versions:**
disease_ontology.json -  v5.4.0
cell_line.json -  v15.1.0
donor_organism.json -  v5.6.0
specimen_from_organism.json -  v10.5.0
**Functionalities**
- [Expand disease ontology to include phenotype](https://github.com/HumanCellAtlas/metadata-schema/issues/1460#)
- fixed release_prepare.py to correctly fill in changelog.md
No reviews needed as this is a release
=> Release from staging to master 2022-05-24

tests/schema.test.js
Increases timeout for schema tests to 60 seconds.
=> Increase timeout of schema-tests

src/schema_linter.py
Fixed the linter to allow for schema property, "dependentRequired".
More information on the keyword [here](https://json-schema.org/understanding-json-schema/reference/conditionals.html#dependentrequired)
=> [HOTFIX]Allowed dependentRequired property in the schema linter.

.github/workflows/schema-tests.yml, Makefile, docs/jsonBrowser/core.md, docs/jsonBrowser/module.md, docs/jsonBrowser/required_fields.md, docs/jsonBrowser/type.md, docs/test_plan.md, src/human_readable_json.py, tests/python/test_human_readable_json.py
Updated `src/human_readable_json.py` to generate the header hyperlinks correctly
ebi-ait/hca-ebi-wrangler-central#846
=> Corrected hyperlink generation for headers.

changelog.md, json_schema/module/ontology/contributor_role_ontology.json, json_schema/versions.json
Hotfixed project role in master
=> hotfix project role master

changelog.md, json_schema/system/links.json, json_schema/update_log.csv, json_schema/versions.json
For `system/links.json` schema:
- Added value `treatment_protocol` to `definitions.protocols.protocol_type`
-This is a minor change needed to create the test data for the `treatment_protocol` addition
=> Added enum value to protocol_type. Fixes #1488.

changelog.md, docs/jsonBrowser/type.md, json_schema/type/biomaterial/donor_organism.json, json_schema/update_log.csv, json_schema/versions.json
For `type/biomaterial/donor_organism.json` schema:
- Fixed type in gestational age description 
- This is a patch change so shouldn't effect anything downstream.
=> Fixed typo in gestational age description. Fixes #1194

changelog.md, docs/jsonBrowser/module.md, json_schema/module/project/hca_bionetwork.json, json_schema/update_log.csv, json_schema/versions.json
For `module/project/hca_bionetworks` schema:
- Added 5 new atlas to `hca_tissue_atlas` field enum
=> Added new enum values to hca_bionetworks.hca_tissue_atlas

changelog.md, docs/jsonBrowser/type.md, json_schema/type/biomaterial/specimen_from_organism.json, json_schema/versions.json
For type/protocol/analysis/analysis_protocol.json schema:
- v10.1.0: Added alignment_software & alignment_software_version optional fields
No reviews needed as this is a release
=> Release from staging to master 2023-11-07

changelog.md, docs/jsonBrowser/type.md, json_schema/type/protocol/analysis/analysis_protocol.json, json_schema/versions.json
For type/protocol/analysis/analysis_protocol.json schema:
- v10.2.0: Added gene_annotation_version field 
No reviews needed as this is a release
=> Release from staging to master 2024-02-05

changelog.md, docs/jsonBrowser/type.md, json_schema/type/biomaterial/specimen_from_organism.json, json_schema/type/protocol/analysis/analysis_protocol.json, json_schema/versions.json
Release notes
For type/protocol/analysis/analysis_protocol.json schema:
* v10.3.0: Added intron_inclusion field
No reviews needed as this is a release
=> Release from staging to master 2024-04-16

changelog.md, docs/jsonBrowser/module.md, docs/jsonBrowser/required_fields.md, json_schema/module/biomaterial/medical_history.json, json_schema/module/ontology/medication_ontology.json, json_schema/update_log.csv, json_schema/versions.json
For `medical_history.json` schema:
- `medication` field from **string** to **array of ontology**
For `medication_ontology.json` schema:
- Create ontology module
- Need 5 Reviewers to approve because this is a **major** update
=> Update medication field in medical_history module

changelog.md, docs/jsonBrowser/module.md, json_schema/module/project/hca_bionetwork.json, json_schema/update_log.csv, json_schema/versions.json
#1600 
For `hca_bionetwork.json` schema:
- Remove enum value `Oral & Craniofacial`
- Add enum value `Oral and Craniofacial` 
- Need 5 Reviewers to approve because this is a major update
=> Replace enum value in hca_bionetwork name.

changelog.md, docs/jsonBrowser/type.md, json_schema/type/biomaterial/cell_suspension.json, json_schema/update_log.csv, json_schema/versions.json
fix #1608 
For `cell_suspension.json` schema:
- Field name: processing_institute
- Field description: Institute where the biomaterial was processed.
- Field type: string
- Required: no
- Need 4 Reviewers to approve because this is a **minor** update
=> Added processing_institute in cell_suspension. Fix #1608

changelog.md, docs/jsonBrowser/type.md, json_schema/type/biomaterial/specimen_from_organism.json, json_schema/update_log.csv, json_schema/versions.json, src/schema_linter.py
fixes #1614 
For `type/biomaterial/specimen_from_organism.json` schema:
- `v11.0.0.`: fix incorrect reference for `collection_institute`
- Need 4 Reviewers to approve because this is a **major** update
=> Fix collection_institute reference typo 
